import { NextFunction, Response } from 'express';
import { z } from 'zod';
import { AuthenticatedRequest } from '../middleware/auth.middleware';
import { quizService } from '../services/quiz.service';

const generateQuizInputSchema = z.object({
  documentIds: z.array(z.string().min(1)).min(1, 'At least one document must be selected'),
  questionCount: z.coerce.number().int().min(1).max(15).optional().default(5),
});

const generateFocusedQuizInputSchema = z.object({
  documentIds: z.array(z.string().min(1)).optional(),
  questionCount: z.coerce.number().int().min(1).max(15).optional().default(5),
  targetTopics: z.array(z.string().min(1)).optional(),
});

const submitQuizInputSchema = z.object({
  answers: z.array(
    z.object({
      questionIndex: z.number().int().min(0),
      selectedOptionIndex: z.number().int().min(-1).max(3),
    })
  ),
});

export class QuizController {
  /**
   * POST /api/quiz/generate
   * Generates a multi-question quiz sampled across selected documents.
   */
  public async generate(
    req: AuthenticatedRequest,
    res: Response,
    next: NextFunction
  ): Promise<void> {
    try {
      const parsed = generateQuizInputSchema.parse(req.body);
      const quiz = await quizService.generateQuiz(
        req.userId as string,
        parsed.documentIds,
        parsed.questionCount
      );

      res.status(201).json({
        message: 'Quiz generated successfully',
        quiz,
      });
    } catch (error) {
      next(error);
    }
  }

  /**
   * POST /api/quiz/generate-focused
   * Generates a focused quiz weighted toward the student's weakest topics.
   */
  public async generateFocused(
    req: AuthenticatedRequest,
    res: Response,
    next: NextFunction
  ): Promise<void> {
    try {
      const parsed = generateFocusedQuizInputSchema.parse(req.body);
      const quiz = await quizService.generateFocusedQuiz(
        req.userId as string,
        parsed.documentIds,
        parsed.questionCount,
        parsed.targetTopics
      );

      res.status(201).json({
        message: 'Focused practice quiz generated successfully',
        quiz,
      });
    } catch (error) {
      next(error);
    }
  }

  /**
   * GET /api/quiz/:id
   * Retrieves a quiz for active taking (masks correct answers).
   */
  public async getForTaking(
    req: AuthenticatedRequest,
    res: Response,
    next: NextFunction
  ): Promise<void> {
    try {
      const quiz = await quizService.getQuizForTaking(
        req.userId as string,
        req.params.id as string
      );
      res.status(200).json({ quiz });
    } catch (error) {
      next(error);
    }
  }

  /**
   * POST /api/quiz/:id/submit
   * Evaluates submitted answers entirely server-side and saves a QuizAttempt.
   */
  public async submit(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const parsed = submitQuizInputSchema.parse(req.body);
      const result = await quizService.submitQuiz(
        req.userId as string,
        req.params.id as string,
        parsed.answers
      );

      res.status(200).json({
        message: 'Quiz evaluated successfully',
        attempt: result.attempt,
        quiz: result.quiz,
      });
    } catch (error) {
      next(error);
    }
  }

  /**
   * GET /api/quiz
   * Lists all quizzes generated by the authenticated user.
   */
  public async list(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const quizzes = await quizService.getUserQuizzes(req.userId as string);
      res.status(200).json({ quizzes });
    } catch (error) {
      next(error);
    }
  }
}

export const quizController = new QuizController();
